using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KKDEnvanter.myModels
{
    class MyVariables
    {

        public int baretEtiler {  get; set; }
        public int baretEmirgan { get; set; }
        public int RLbaretEtiler { get; set; }
        public int RLbaretEmirgan { get; set; }
        public int YGbaretEtiler { get; set; }
        public int YGbaretEmirgan { get; set; }
        public int lambaEtiler { get; set; }
        public int lambaEmirgan { get; set; }
        public int ceneBandiEtiler { get; set; }
        public int cenebandiEmirgan { get; set; }
        public int terBandiEtiler { get; set; }
        public int terBandiEmirgan { get; set; }
        public int kordonTikacEtiler { get; set; }
        public int kordonTikacEmirgan { get; set; }
        public int mansonluEtiler { get; set; }
        public int mansonluEmirgan { get; set; }
        public int tozEtiler { get; set; }
        public int tozEmirgan { get; set; }
        public int gustuTozEtiler   { get; set; }
        public int gustuTozEmirgan { get; set; }
        public int kaynakGozEtiler { get; set; }
        public int kaynakGozEmirgan { get;set; }
        public int gustuKaynakEtiler { get;set; }
        public int gustuKaynakEmirgan { get;set; }
        public int karEtiler { get; set; }
        public int karEmirgan { get; set; }
        public int siperEtiler { get; set; }
        public int siperEmirgan { get; set; }
        public int tamMaskeEtiler { get; set; }
        public int tamMaskeEmirgan { get; set; }
        public int tozMaskeEtiler { get; set; }
        public int tozMaskeEmirgan { get; set; }
        public int akEtiler { get; set; }
        public int akEmirgan { get; set; }
        public int gazFiltreEtiler { get; set; }
        public int gazFiltreEmirgan { get; set; }
        public int isEldiveni8Etiler { get; set; }
        public int isEldiveni9Etiler { get; set; }
        public int isEldiveni10Etiler { get; set; }
        public int isEldiveni11Etiler { get; set; }
        public int isEldiveni8Emirgan { get; set; }
        public int isEldiveni9Emirgan { get; set; }
        public int isEldiveni10Emirgan { get; set; }
        public int isEldiveni11Emirgan { get; set; }
        public int kdEldivenEtiler { get; set; }
        public int kdEldivenEmirgan { get; set; }
        public int yalitkanEldEtiler { get; set; }
        public int yalitkenEldEmirgan { get; set; }
        public int YGEldivenEtiler { get; set; }
        public int YGEldivenEmirgan { get; set; }
        public int KaynakEldivenEmirgan { get; set; }
        public int KaynakEldivenEtiler { get; set; }
        public int kaynakOnlukEtiler {  get; set; }
        public int kaynakOnlukEmirgan { get; set; }
        public int asidOnlukEtiler { get; set; }
        public int asidonlukEmirgan { get; set; }
        public int tyvekEtilerS {  get; set; }
        public int tyvekEtilerM { get; set; }
        public int tyvekEtilerl { get; set; }
        public int tyvekEtilerXL { get; set; }
        public int tyvekEtilerXXL { get; set; }
        public int tyvekEmirganS { get; set; }
        public int tyvekEmirganM { get; set; }
        public int tyvekEmirganl { get; set; }
        public int tyvekEmirganXL { get; set; }
        public int tyvekEmirganXXL { get; set; }
        public int yelekEtilerS { get; set; }
        public int yelekEtilerM { get; set; }
        public int yelekEtilerl { get; set; }
        public int yelekEtilerXL { get; set; }
        public int yelekEtilerXXL { get; set; }
        public int yelekEmirganS { get; set; }
        public int yelekEmirganM { get; set; }
        public int yelekEmirganl { get; set; }
        public int yelekEmirganXL { get; set; }
        public int yelekEmirganXXL { get; set; }
        public int kislikAyakkabiEtiler36 { get; set; }
        public int kislikAyakkabiEtiler37 { get; set; }
        public int kislikAyakkabiEtiler38 { get; set; }
        public int kislikAyakkabiEtiler39 { get; set; }
        public int kislikAyakkabiEtiler40 { get; set; }
        public int kislikAyakkabiEtiler41 { get; set; }
        public int kislikAyakkabiEtiler42 { get; set; }
        public int kislikAyakkabiEtiler43 { get; set; }
        public int kislikAyakkabiEtiler44 { get; set; }
        public int kislikAyakkabiEtiler45 { get; set; }
        public int kislikAyakkabiEtiler46 { get; set; }
        public int kislikAyakkabiEtiler47 { get; set; }
        public int kislikAyakkabiEtiler48 { get; set; }
        public int kislikAyakkabiEmirgan36 { get; set; }
        public int kislikAyakkabiEmirgan37 { get; set; }
        public int kislikAyakkabiEmirgan38 { get; set; }
        public int kislikAyakkabiEmirgan39 { get; set; }
        public int kislikAyakkabiEmirgan40 { get; set; }
        public int kislikAyakkabiEmirgan41 { get; set; }
        public int kislikAyakkabiEmirgan42 { get; set; }
        public int kislikAyakkabiEmirgan43 { get; set; }
        public int kislikAyakkabiEmirgan44 { get; set; }
        public int kislikAyakkabiEmirgan45 { get; set; }
        public int kislikAyakkabiEmirgan46 { get; set; }
        public int kislikAyakkabiEmirgan47 { get; set; }
        public int kislikAyakkabiEmirgan48 { get; set; }
        public int yazlikAyakkabiEtiler36 { get; set; }
        public int yazlikAyakkabiEtiler37 { get; set; }
        public int yazlikAyakkabiEtiler38 { get; set; }
        public int yazlikAyakkabiEtiler39 { get; set; }
        public int yazlikAyakkabiEtiler40 { get; set; }
        public int yazlikAyakkabiEtiler41 { get; set; }
        public int yazlikAyakkabiEtiler42 { get; set; }
        public int yazlikAyakkabiEtiler43 { get; set; }
        public int yazlikAyakkabiEtiler44 { get; set; }
        public int yazlikAyakkabiEtiler45 { get; set; }
        public int yazlikAyakkabiEtiler46 { get; set; }
        public int yazlikAyakkabiEtiler47 { get; set; }
        public int yazlikAyakkabiEtiler48 { get; set; }
        public int yazlikAyakkabiEmirgan36 { get; set; }
        public int yazlikAyakkabiEmirgan37 { get; set; }
        public int yazlikAyakkabiEmirgan38 { get; set; }
        public int yazlikAyakkabiEmirgan39 { get; set; }
        public int yazlikAyakkabiEmirgan40 { get; set; }
        public int yazlikAyakkabiEmirgan41 { get; set; }
        public int yazlikAyakkabiEmirgan42 { get; set; }
        public int yazlikAyakkabiEmirgan43 { get; set; }
        public int yazlikAyakkabiEmirgan44 { get; set; }
        public int yazlikAyakkabiEmirgan45 { get; set; }
        public int yazlikAyakkabiEmirgan46 { get; set; }
        public int yazlikAyakkabiEmirgan47 { get; set; }
        public int yazlikAyakkabiEmirgan48 { get; set; }
        public int YGCizmeEtiler36 { get; set; }
        public int YGCizmeEtiler37 { get; set; }
        public int YGCizmeEtiler38 { get; set; }
        public int YGCizmeEtiler39 { get; set; }
        public int YGCizmeEtiler40 { get; set; }
        public int YGCizmeEtiler41 { get; set; }
        public int YGCizmeEtiler42 { get; set; }
        public int YGCizmeEtiler43 { get; set; }
        public int YGCizmeEtiler44 { get; set; }
        public int YGCizmeEtiler45 { get; set; }
        public int YGCizmeEtiler46 { get; set; }
        public int YGCizmeEtiler47 { get; set; }
        public int YGCizmeEtiler48 { get; set; }
        public int YGCizmeEmirgan36 { get; set; }
        public int YGCizmeEmirgan37 { get; set; }
        public int YGCizmeEmirgan38 { get; set; }
        public int YGCizmeEmirgan39 { get; set; }
        public int YGCizmeEmirgan40 { get; set; }
        public int YGCizmeEmirgan41 { get; set; }
        public int YGCizmeEmirgan42 { get; set; }
        public int YGCizmeEmirgan43 { get; set; }
        public int YGCizmeEmirgan44 { get; set; }
        public int YGCizmeEmirgan45 { get; set; }
        public int YGCizmeEmirgan46 { get; set; }
        public int YGCizmeEmirgan47 { get; set; }
        public int YGCizmeEmirgan48 { get; set; }
        public int CizmeEtiler36 { get; set; }
        public int CizmeEtiler37 { get; set; }
        public int CizmeEtiler38 { get; set; }
        public int CizmeEtiler39 { get; set; }
        public int CizmeEtiler40 { get; set; }
        public int CizmeEtiler41 { get; set; }
        public int CizmeEtiler42 { get; set; }
        public int CizmeEtiler43 { get; set; }
        public int CizmeEtiler44 { get; set; }
        public int CizmeEtiler45 { get; set; }
        public int CizmeEtiler46 { get; set; }
        public int CizmeEtiler47 { get; set; }
        public int CizmeEtiler48 { get; set; }
        public int CizmeEmirgan36 { get; set; }
        public int CizmeEmirgan37 { get; set; }
        public int CizmeEmirgan38 { get; set; }
        public int CizmeEmirgan39 { get; set; }
        public int CizmeEmirgan40 { get; set; }
        public int CizmeEmirgan41 { get; set; }
        public int CizmeEmirgan42 { get; set; }
        public int CizmeEmirgan43 { get; set; }
        public int CizmeEmirgan44 { get; set; }
        public int CizmeEmirgan45 { get; set; }
        public int CizmeEmirgan46 { get; set; }
        public int CizmeEmirgan47 { get; set; }
        public int CizmeEmirgan48 { get; set; }
        public int KasikCizmeEtiler36 { get; set; }
        public int KasikCizmeEtiler37 { get; set; }
        public int KasikCizmeEtiler38 { get; set; }
        public int KasikCizmeEtiler39 { get; set; }
        public int KasikCizmeEtiler40 { get; set; }
        public int KasikCizmeEtiler41 { get; set; }
        public int KasikCizmeEtiler42 { get; set; }
        public int KasikCizmeEtiler43 { get; set; }
        public int KasikCizmeEtiler44 { get; set; }
        public int KasikCizmeEtiler45 { get; set; }
        public int KasikCizmeEtiler46 { get; set; }
        public int KasikCizmeEtiler47 { get; set; }
        public int KasikCizmeEtiler48 { get; set; }
        public int KasikCizmeEmirgan36 { get; set; }
        public int KasikCizmeEmirgan37 { get; set; }
        public int KasikCizmeEmirgan38 { get; set; }
        public int KasikCizmeEmirgan39 { get; set; }
        public int KasikCizmeEmirgan40 { get; set; }
        public int KasikCizmeEmirgan41 { get; set; }
        public int KasikCizmeEmirgan42 { get; set; }
        public int KasikCizmeEmirgan43 { get; set; }
        public int KasikCizmeEmirgan44 { get; set; }
        public int KasikCizmeEmirgan45 { get; set; }
        public int KasikCizmeEmirgan46 { get; set; }
        public int KasikCizmeEmirgan47 { get; set; }
        public int KasikCizmeEmirgan48 { get; set; }
        public int ParasutEtilerS { get; set; }
        public int ParasutEtilerM { get; set; }
        public int ParasutEtilerl { get; set; }
        public int ParasutEtilerXL { get; set; }
        public int ParasutEtilerXXL { get; set; }
        public int ParasutEmirganS { get; set; }
        public int ParasutEmirganM { get; set; }
        public int ParasutEmirganl { get; set; }
        public int ParasutEmirganXL { get; set; }
        public int ParasutEmirganXXL { get; set; }
        public int BelEtiler {  get; set; }
        public int BelEmirgan { get; set; }
        public int perlonEtiler {  get; set; }
        public int perlonEmirgan { get; set; }
        public int karabinaEtiler { get; set; }
        public int karabineEmirgan { get; set; }
        public int sapanEtiler { get; set; }
        public int sapanEmirgan { get; set; }
        public int celikHalatEtiler { get; set; }
        public int celikhalatEmirgan { get; set; }
        public int makaraEtiler { get; set; }
        public int makaraEmirgan { get; set; }
        public int halat50Etiler { get; set; }
        public int halat50Emirgan { get; set; }
        public int halat100Etiler { get; set; }
        public int halat100Emirgan { get; set; }
        public int jumarEtiler { get; set; }
        public int jumarEmirgan { get; set; }
        public int lanyardEtiler { get; set; }
        public int lanyardEmirgan { get; set; }
        public int halatEtiler { get;set; }
        public int halatEmirgan { get; set; }
        public int ayakcakEtiler { get; set; }
        public int ayakcakEmirgan { get; set; }
        public int cantaEtiler { get; set; }
        public int cantaEmirgan { get; set; }
        public int tabelaEtiler { get; set; }
        public int tabelaEmirgan { get; set; }
        public int delinatorEtiler { get; set; }
        public int delintorEmirgan { get; set; }
        public int duba50Etiler { get; set; }
        public int duba50Emirgan { get; set; }
        public int duba90Etiler { get; set; }
        public int duba90Emirgan { get; set; }
        public int seritEtiler { get; set; }
        public int seritEmirgan { get; set; }
        public int bantEtiler { get; set; }
        public int bantEmirgan { get; set; }
        public int absorbEtiler { get; set; }
        public int absorbEmirgan { get; set; }
        public int paspasEtiler { get; set; }
        public int paspasEmirgan { get; set; }
        public int dusEtiler { get; set; }
        public int dusEmirgan { get; set; }
        public int aparatEtiler { get; set; }
        public int aparatEmirgan { get; set; }
        public int jelEtiler { get; set; }
        public int jelEmirgan { get; set; }
        public int Diger1Etiler { get; set; }
        public int Diger1Emirgan { get; set; }
        public int Diger2Etiler { get; set; }
        public int Diger2Emirgan { get; set; }
        public int Diger3Etiler { get; set; }
        public int Diger3Emirgan { get; set; }

        public int SgiDiger1Etiler { get; set; }
        public int SgiDiger1Emirgan { get; set; }
        public int SgiDiger2Etiler { get; set; }
        public int SgiDiger2Emirgan { get; set; }
        public int SgiDiger3Etiler { get; set; }
        public int SgiDiger3Emirgan { get; set; }

    }
}
